export interface TestimonialSeed {
  quote: string;
  authorName: string;
  authorTitle: string;
  order: number;
  published: boolean;
}

/** Reproduced verbatim from ibill.ae. */
export const TESTIMONIALS: TestimonialSeed[] = [
  {
    quote:
      "The Salon Assist App has completely changed how I manage my team. The productivity tracking feature gives me real-time insights into each employee's performance, helping me identify top performers and areas that need improvement. Plus, the detailed revenue reports have made it so much easier to track our financial growth. It's an invaluable tool for any salon owner.",
    authorName: "Emily S.",
    authorTitle: "Salon Owner",
    order: 1,
    published: true,
  },
  {
    quote:
      "Thanks to the Salon Assist App, I can now monitor my staff's productivity with ease. The app's performance metrics provide a clear picture of how each team member is contributing to our bottom line. The ability to see individual revenue generated by each stylist has helped us set more targeted goals and reward our top performers. Highly recommended for salon owners looking to optimize their business.",
    authorName: "Daniel R.",
    authorTitle: "Salon Owner",
    order: 2,
    published: true,
  },
  {
    quote:
      "With the Salon Assist App, tracking employee productivity and revenue has never been easier. I love how I can see which services are bringing in the most income and which employees are driving that success. The data provided has been crucial in making informed decisions about staffing and promotions. This app is a must-have for serious salon owners.",
    authorName: "Hannah T.",
    authorTitle: "Salon Owner",
    order: 3,
    published: true,
  },
  {
    quote:
      "The Salon Assist App provides a level of transparency and control over my business that I didn't have before. I can easily track how each stylist is performing in terms of both productivity and revenue generation. This insight has allowed me to tailor our strategies for growth and reward those who contribute the most to our success. It's been a game-changer for our salon.",
    authorName: "Michael B.",
    authorTitle: "Salon Owner",
    order: 4,
    published: true,
  },
  {
    quote:
      "One of the best features of the Salon Assist App is its ability to track employee productivity and revenue in detail. It's been incredibly helpful in understanding how each team member contributes to the overall business. The insights from the app have empowered us to make better decisions on incentives and staff development. A brilliant tool for any salon owner.",
    authorName: "Olivia M.",
    authorTitle: "Salon Owner",
    order: 5,
    published: true,
  },
];
